# Generated by Django 4.0.3 on 2023-09-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appiontment',
            new_name='Appointment',
        ),
    ]
