# Generated by Django 4.0.3 on 2023-09-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_resaon_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Scheduled', max_length=200),
        ),
    ]
